name: Pruebas Unitarias

on:
  push:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Código
      uses: actions/checkout@v2

    - name: Configurar el entorno
      run: |
        # Configura tu entorno de pruebas aquí, por ejemplo, instala las dependencias.
        npm install
      working-directory: ./tu-directorio-de-código

    - name: Ejecutar Pruebas Unitarias
      run: |
        # Ejecuta tus pruebas unitarias aquí.
        npm test
      working-directory: ./tu-directorio-de-código
