name: Pruebas Unitarias

on:
  pull_request:
    branches:
      - main

jobs:
  pruebas_unitarias:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout del código
        uses: actions/checkout@v2

      - name: Configurar entorno
        run: |
          # Configura tu entorno aquí

      - name: Ejecutar pruebas unitarias
        run: |
          # Comando para ejecutar las pruebas unitarias

  merge-blocking:
    runs-on: ubuntu-latest
    needs: pruebas_unitarias
    steps:
      - name: Verificar errores en pruebas unitarias
        run: |
          # Comando para verificar errores en las pruebas unitarias
          # Puedes usar scripts o herramientas para esto

      - name: Comentar en el PR si hay errores
        if: ${{ failure() }}
        uses: actions/github-script@v5
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            const context = github.context;
            const issueComment = context.issue;
            github.issues.createComment({
              ...issueComment,
              body: 'Se encontraron errores en las pruebas unitarias. No se puede fusionar hasta que se corrijan.',
            });
name: Pruebas Unitarias

on:
  pull_request:
    branches:
      - main

jobs:
  pruebas_unitarias:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout del código
        uses: actions/checkout@v2

      - name: Configurar entorno
        run: |
          # Configura tu entorno aquí

      - name: Ejecutar pruebas unitarias
        run: |
          # Comando para ejecutar las pruebas unitarias

  merge-blocking:
    runs-on: ubuntu-latest
    needs: pruebas_unitarias
    steps:
      - name: Verificar errores en pruebas unitarias
        run: |
          # Comando para verificar errores en las pruebas unitarias
          # Puedes usar scripts o herramientas para esto

      - name: Comentar en el PR si hay errores
        if: ${{ failure() }}
        uses: actions/github-script@v5
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            const context = github.context;
            const issueComment = context.issue;
            github.issues.createComment({
              ...issueComment,
              body: 'Se encontraron errores en las pruebas unitarias. No se puede fusionar hasta que se corrijan.',
            });
