name: Tests

on:
  push:
    branches:
      - main # Reemplaza con tu rama principal

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        with:
          persist-credentials: false

      - name: Set Git Config
        run: |
          git config --global user.email "actions@github.com"
          git config --global user.name "GitHub Actions"

      - name: Use Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '14' # Puedes cambiar la versión de Node.js si es necesario

      - name: Install dependencies
        run: npm install # O yarn install si usas yarn

      - name: Run tests
        run: npm test # O yarn test si usas yarn

      - name: Check test results
        run: |
          if [ ${{ job.status }} != "success" ]; then
            echo "Las pruebas han fallado. No se realizarán cambios en el repositorio."
            exit 1
          fi

      - name: Realizar cambios en el repositorio (solo si las pruebas pasan)
        run: |
          # Coloca aquí tus comandos para realizar cambios en el repositorio si es necesario
